name: awscli

on:
  push:
    branches:
      - main
      - 'feature/**'

permissions:
  id-token: write
  contents: read

env:
  AWS_ROLE_ARN: arn:aws:iam::384657981262:role/GithubActionsTestByOIDC
  ECR_REGISTRY: 384657981262.dkr.ecr.ap-northeast-1.amazonaws.com
  ECR_REPOSITORY: tf-app
jobs:
  get-caller-identity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from test
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform fmt
        id: fmt
        working-directory: .
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id : init
        working-directory: .
        run: terraform init

      - name: Terraform Plan
        id: plan
        working-directory: .
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        working-directory: .
        run: terraform apply -auto-approve

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ECR_REGISTRY }}

      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
